run-dist:
	./build/install/app/bin/app
clean:
	./gradlew clean
build:
	./gradlew build --no-problems-report
test:
	./gradlew test
run:
	./gradlew run
installDist:
	./gradlew installDist
check:
	./gradlew check
.PHONY:build