name: test project
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Run test project"
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13" # Quotes required to prevent YAML converting to number
      - name: Build with Gradle
        run: ./gradlew build --no-problems-report
        working-directory: ./app
      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v2
        env:
          QLTY_COVERAGE_TOKEN: ${{secrets.QLTY_COVERAGE_TOKEN}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          workingDirectory: ./app
          coverageCommand: ./gradlew jacocoTestReport --no-problems-report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          workingDirectory: ./app
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/app .gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
        working-directory: ./app
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/app/build/test-results/test/TEST-*.xml'
